// data-inkoop.js — gedeelde data (Facilitaire Inkoop)
window.INKOOP = window.INKOOP || {};
INKOOP.cats = [
  {
    "key": "basis",
    "label": "Basisprincipes",
    "short": "Basisprincipes",
    "color": "#3b82f6"
  },
  {
    "key": "vanweele",
    "label": "Van Weele (6 stappen)",
    "short": "Van Weele",
    "color": "#10b981"
  },
  {
    "key": "tactisch",
    "label": "Tactische inkoop",
    "short": "Tactische inkoop",
    "color": "#d97706"
  },
  {
    "key": "operationeel",
    "label": "Operationele inkoop",
    "short": "Operationele inkoop",
    "color": "#8b5cf6"
  },
  {
    "key": "strategie",
    "label": "Strategie & Contracten",
    "short": "Strategie",
    "color": "#ef4444"
  },
  {
    "key": "markt",
    "label": "Marktonderzoek & PMI",
    "short": "Marktonderzoek",
    "color": "#f97316"
  },
  {
    "key": "digitaal",
    "label": "Digitalisering",
    "short": "Digitalisering",
    "color": "#ec4899"
  }
];
INKOOP.begrippen = [

  /* ══════════════════════════════════════════
     1. BASISPRINCIPES (Week 1)
  ══════════════════════════════════════════ */
  {cat:"basis", term:"Inkoop",
   def:"Het van externe bronnen betrekken van alle goederen en diensten die noodzakelijk zijn voor de bedrijfsvoering en de instandhouding van een organisatie, tegen de meest gunstige voorwaarden."},
  {cat:"basis", term:"Inkoopfunctie",
   def:"Het organisatiebrede proces van inkoop — omvat meer dan alleen de inkoopafdeling. Factuurafhandeling (Finance), inhuren tijdelijk personeel (HRM) en boeken van transport (Logistiek) vallen buiten de afdeling maar zijn onderdeel van de inkoopfunctie."},
  {cat:"basis", term:"Spin in het web",
   def:"Metafoor voor de inkoper: inkoop raakt alle bedrijfsfuncties en vormt de schakel tussen de interne organisatie en de externe leveranciersmarkt."},
  {cat:"basis", term:"Primaire (directe) inkoop",
   def:"Inkoop van goederen en diensten die rechtstreeks terechtkomen in het eindproduct of de kernactiviteit van de organisatie. Bijv. grondstoffen voor een fabriek, medicijnen in een ziekenhuis."},
  {cat:"basis", term:"Indirecte inkoop",
   def:"Inkoop van alles wat de organisatie nodig heeft om te functioneren, maar niet direct in het eindproduct of de kernactiviteit terechtkomt. Bijv. ICT, schoonmaak, catering, beveiliging, kantoorartikelen."},
  {cat:"basis", term:"Facilitaire inkoop",
   def:"Een specifieke vorm van indirecte inkoop: het inkopen van facilitaire diensten en producten (schoonmaak, catering, beveiliging, bedrijfskleding, hospitality). Dit is het werkterrein van de Facility Manager. Niet álle indirecte inkoop is facilitair (bijv. ICT en HR-inhuur vallen meestal buiten facilitair)."},
  {cat:"basis", term:"MRO (Maintenance, Repair & Operations)",
   def:"Productcategorie binnen indirecte inkoop: goederen en diensten voor dagelijks onderhoud, reparatie en bedrijfsvoering (smeermiddelen, reserveonderdelen, gereedschap, schoonmaakartikelen). MRO wordt vaak via indirecte/facilitaire inkoop ingekocht, maar is geen synoniem ervan: het is een productsoort, niet de inkoopfunctie zelf."},
  {cat:"basis", term:"Inkoopquote",
   def:"Percentage van de omzet dat besteed wordt aan inkoop. Formule: (totale inkoopkosten / totale omzet) × 100%",
   formula:"Inkoopquote = (inkoopkosten / omzet) × 100%"},
  {cat:"basis", term:"Hefboomwerking van inkoop",
   def:"Bij een inkoopquote van 50% en nettomarge van 5% levert 1% inkoopbesparing evenveel resultaatverbetering op als ±10% omzetgroei. Inkoop heeft directe invloed op het bedrijfsresultaat."},
  {cat:"basis", term:"Make-or-buy beslissing",
   def:"De meest fundamentele strategische inkoopbeslissing: voert de organisatie een activiteit zelf uit (make) of koopt ze die in bij een externe partij (buy)? Kernactiviteiten worden vaak intern gehouden; ondersteunende activiteiten zijn kandidaten voor uitbesteding."},
  {cat:"basis", term:"Maverick buying",
   def:"Medewerkers die buiten de gesloten contracten om inkopen. Gevolg: volume- en kortingsvoordelen gaan verloren, administratieve chaos en een slechtere onderhandelingspositie bij de volgende aanbesteding."},
  {cat:"basis", term:"Publieke inkoop",
   def:"Inkoop door overheidsorganisaties (gemeente, ziekenhuis, school, ministerie). Gericht op maatschappelijke doelstellingen. Boven drempelwaarden verplicht Europees aanbesteden met gelijke kansen voor leveranciers."},
  {cat:"basis", term:"Private inkoop",
   def:"Inkoop door private organisaties (bedrijven, instellingen). Gericht op winst of continuïteit. Vrij in leverancierskeuze en onderhandelingswijze."},
  {cat:"basis", term:"Aanbesteding",
   def:"Formeel proces waarmee een opdrachtgever de markt benadert om leveranciers te selecteren. Verplicht bij publieke organisaties boven bepaalde drempelwaarden. Garandeert gelijke behandeling van inschrijvers."},
  {cat:"basis", term:"Centrale inkoop",
   def:"Één centrale afdeling is verantwoordelijk voor alle inkoop van de organisatie. Voordeel: maximale schaalvoordelen en uniforme contracten. Nadeel: ver van de business, beperkte lokale zeggenschap."},
  {cat:"basis", term:"Decentrale inkoop",
   def:"Afdelingen of businessunits kopen zelf in. Voordeel: lokale kennis en betrokkenheid. Nadeel: verlies van schaalvoordelen en mogelijk hogere prijzen per eenheid."},
  {cat:"basis", term:"Hybride inkoop (coördinatie)",
   def:"Combinatie van centrale regie en decentrale uitvoering. Een inkoopcoördinator bewaakt de kaders terwijl afdelingen lokaal inkopen. Combineert schaalvoordelen met flexibiliteit."},
  {cat:"basis", term:"Vier primaire taken van inkoop",
   def:"1. Operationele excellentie (continuïteit), 2. Realiseren van inkoopbesparingen, 3. Verminderen van risico's in de toeleveringsketen, 4. Bijdragen aan innovatie en waardecreatie."},
  {cat:"basis", term:"Organisatie-inkoop vs. consumenteninkoop",
   def:"Organisatie-inkoop is overwegend rationeel, gestructureerd en langdurig. Consumenteninkoop is vaker emotioneel, impulsief en kortdurend. Inkopen voor organisaties vereist specifieke expertise en andere aanpak."},

  /* ══════════════════════════════════════════
     2. VAN WEELE — 6 STAPPEN (Week 2-3)
  ══════════════════════════════════════════ */
  {cat:"vanweele", term:"Lineair inkoopproces van Van Weele",
   def:"Het inkoopproces bestaat uit zes stappen: 1. Specificeren → 2. Selecteren → 3. Contracteren (tactisch, éénmalig) → 4. Bestellen → 5. Bewaken → 6. Nazorg & Evaluatie (operationeel, herhaald)."},
  {cat:"vanweele", term:"Tactische inkoop (stappen 1-3)",
   def:"De éénmalige, strategische fase van het inkoopproces: specificeren, selecteren en contracteren. Bepaalt wat, bij wie en onder welke voorwaarden wordt ingekocht."},
  {cat:"vanweele", term:"Operationele inkoop (stappen 4-6)",
   def:"De herhaalde, uitvoerende fase van het inkoopproces: bestellen, bewaken en nazorg & evaluatie. Wordt gedurende de looptijd van een contract steeds opnieuw doorlopen."},
  {cat:"vanweele", term:"Stap 1: Specificeren",
   def:"Bepalen wát er ingekocht moet worden. Primair de verantwoordelijkheid van de gebruiker/budgethouder. De inkoper zorgt dat de specificatie objectief, leveranciersneutraal en eenduidig is."},
  {cat:"vanweele", term:"Stap 2: Selecteren",
   def:"Het in kaart brengen van de markt, opstellen van shortlist, aanvragen van offertes (RFQ) en kiezen van de meest geschikte leverancier op basis van een gestructureerde beoordelingsmethode."},
  {cat:"vanweele", term:"Stap 3: Contracteren",
   def:"Onderhandelen over prijs en voorwaarden, en de afspraken vastleggen in een contract. Bevat afspraken over prijs, kwaliteit, levering, KPI's, SLA's en exitclausules."},
  {cat:"vanweele", term:"Stap 4: Bestellen",
   def:"Het plaatsen van een inkooporder bij de gecontracteerde leverancier. De inkooporder is de officiële bevestiging van een bestelling met alle relevante gegevens."},
  {cat:"vanweele", term:"Stap 5: Bewaken (orderbewaking)",
   def:"Toezicht houden op tijdige, volledige levering op het afgesproken leverpunt, met de afgesproken documenten. Drie methoden: exception expediting, routine statuscheck, advanced statuscheck."},
  {cat:"vanweele", term:"Stap 6: Nazorg & Evaluatie",
   def:"Factuurcontrole via three-way matching, afhandeling van reclames en leveranciersbeoordeling. Basis voor toekomstige selectiebeslissingen."},

  /* ══════════════════════════════════════════
     3. TACTISCHE INKOOP — BEGRIPPEN (Week 2)
  ══════════════════════════════════════════ */
  {cat:"tactisch", term:"Functionele specificatie",
   def:"Beschrijft wát een product of dienst moet doen (niet hóe). Geeft leveranciers ruimte voor creatieve oplossingen. Voorbeeld: 'De ruimte moet schoon zijn.'"},
  {cat:"tactisch", term:"Programma van Eisen (PvE)",
   def:"Verdere detaillering van de functionele specificatie met SMART-geformuleerde eisen, richtbudget en randvoorwaarden. Bevat prestatie-, technische, kwaliteits-, logistieke en duurzaamheidseisen."},
  {cat:"tactisch", term:"Technische specificatie",
   def:"Uitwerking van alle specifieke technische eisen: maatvoering, materialen, normen, levertijden, certificeringen. Het meest gedetailleerde niveau van specificeren."},
  {cat:"tactisch", term:"Eisen vs. wensen",
   def:"Eisen zijn knock-outcriteria — leveranciers die niet aan eisen voldoen worden uitgesloten. Wensen zijn nice-to-have criteria die wél meewegen in de beoordeling maar niet elimineren."},
  {cat:"tactisch", term:"Best Value Procurement (BVP)",
   def:"Inkoopstrategie waarbij de nadruk ligt op de best mogelijke waarde, niet op de laagste prijs. De aanbieder die de meeste waarde levert voor de gevraagde prijs wint, ook als dat niet de goedkoopste is."},
  {cat:"tactisch", term:"RFI (Request for Information)",
   def:"Informatieverzoek aan potentiële leveranciers in de oriëntatiefase. Niet bindend. Gebruikt voor marktconsultatie en prekwalificatie: longlist → shortlist."},
  {cat:"tactisch", term:"RFQ (Request for Quotation)",
   def:"Formele offerteaanvraag bij de shortlist van leveranciers. Bindend bij gunning. Bevat alle eisen en criteria waarop beoordeeld wordt."},
  {cat:"tactisch", term:"Prekwalificatie",
   def:"Toetsen of potentiële leveranciers voldoen aan basisvereisten (financiële stabiliteit, certificeringen, referenties) vóórdat een formele offerteaanvraag wordt gedaan. Longlist → shortlist."},
  {cat:"tactisch", term:"Gewogen factorscore / BPKV",
   def:"Offertebeoordelingsmethode waarbij meerdere criteria elk een wegingsfactor krijgen. Scores per criterium worden gewogen opgeteld. Meest gebruikt bij complexe aankopen. BPKV = Best Price to Quality Value."},
  {cat:"tactisch", term:"Indexmethode",
   def:"Offertebeoordelingsmethode waarbij een vaste prijs/kwaliteitsverhouding is vastgesteld (bijv. 50/50). 1% hogere kwaliteit rechtvaardigt 1% hogere prijs."},
  {cat:"tactisch", term:"Waardering in euro's",
   def:"Offertebeoordelingsmethode waarbij kwaliteitsverschillen worden uitgedrukt in euro's en in mindering worden gebracht op de aangeboden prijs. De laagste gecorrigeerde prijs wint."},
  {cat:"tactisch", term:"Accountportfolio",
   def:"Spiegel van de Kraljic-matrix vanuit leveranciersperspectief: hoe segmenteert de leverancier zijn klanten? Core account (hoge omzet, strategisch), Development account (groeiend), Nuisance account (kleine klant, hoge behoefte)."},
  {cat:"tactisch", term:"Resultaatcontract",
   def:"Contract waarbij de leverancier een concreet resultaat garandeert. Betaling is gekoppeld aan het resultaat. Makkelijker toetsbaar — voorkeur van de inkoper."},
  {cat:"tactisch", term:"Inspanningscontract",
   def:"Contract waarbij de leverancier zich inspant maar geen resultaat garandeert (bijv. advocaat, adviseur). Van toepassing als het eindresultaat moeilijk van tevoren te definiëren is."},
  {cat:"tactisch", term:"Vaste prijs (fixed price)",
   def:"Contractvorm waarbij de prijs vooraf is vastgesteld. Het financiële risico ligt bij de leverancier. Vereist een volledig en gedetailleerd PvE."},
  {cat:"tactisch", term:"Regiecontract",
   def:"Contractvorm waarbij achteraf wordt verrekend op basis van uren en materialen. Financieel risico ligt bij de opdrachtgever. Biedt de leverancier geen prikkel voor efficiëntie."},
  {cat:"tactisch", term:"Eenheidsprijscontract",
   def:"Contractvorm met een tarief per prestatie-eenheid (m², uur, stuk). Geschikt voor standaard terugkerende werkzaamheden waarbij volume vooraf onbekend is."},
  {cat:"tactisch", term:"SLA (Service Level Agreement)",
   def:"Meetbare prestatieafspraken over het niveau van dienstverlening. Onderdeel van het contract. Basis voor het beoordelen van de leverancier tijdens de operationele fase."},
  {cat:"tactisch", term:"KPI (Key Performance Indicator)",
   def:"Prestatie-indicator waarmee de kwaliteit van levering wordt gemeten. Wordt gebruikt bij orderbewaking, leveranciersevaluatie en contractmanagement."},
  {cat:"tactisch", term:"Salamitactiek",
   def:"Onderhandelingstactiek waarbij in kleine stappen concessies worden verkregen, zodat de wederpartij niet in één keer het totale verlies ziet."},
  {cat:"tactisch", term:"TCO (Total Cost of Ownership)",
   def:"Alle kosten verbonden aan de aanschaf, het bezit en de afdanking van een product of dienst over de volledige levenscyclus. Omvat pre-transactie-, transactie- en post-transactiekosten — nadrukkelijk niet alleen de aanschafprijs.",
   formula:"TCO = pre-transactie + transactie + post-transactiekosten"},

  /* ══════════════════════════════════════════
     4. OPERATIONELE INKOOP (Week 3)
  ══════════════════════════════════════════ */
  {cat:"operationeel", term:"Inkooporder",
   def:"Officieel document waarmee de koper een bestelling plaatst bij een leverancier na ondertekening van het contract. Bevestigt wat besteld is, hoeveel, tegen welke prijs en wanneer geleverd."},
  {cat:"operationeel", term:"Roundtrip bestelling",
   def:"Bestelwijze waarbij de medewerker winkelt in de webshop van de leverancier; het winkelmandje wordt teruggezonden naar het interne bestelsysteem voor goedkeuring door de budgethouder."},
  {cat:"operationeel", term:"Catalogusbestelling",
   def:"Bestelwijze waarbij de medewerker winkelt in een interne catalogus binnen het bestelsysteem. Snelle route: direct naar budgethouder ter goedkeuring."},
  {cat:"operationeel", term:"Vrije aanvraag",
   def:"Bestelwijze voor niet-standaard bestellingen waarbij de medewerker alle gegevens zelf invult. Langste route: eerst langs Inkoop en Bedrijfsbureau, dan naar budgethouder."},
  {cat:"operationeel", term:"Exception expediting (piepsysteem)",
   def:"Reactieve bewakingsmethode waarbij de inkoper pas actie onderneemt na een probleemsignaal. Nadeel: inkoper loopt altijd achter de feiten aan, wat leidt tot spoedorders en buffervoorraden."},
  {cat:"operationeel", term:"Routine statuscheck",
   def:"Proactieve bewakingsmethode waarbij de inkoper enkele dagen vóór de leverdatum contact opneemt om leverdatum en volledigheid te bevestigen. Eenvoudig en effectief."},
  {cat:"operationeel", term:"Advanced statuscheck",
   def:"Meest proactieve bewakingsmethode: kritische leveranciers geven een gedetailleerde productieplanning; periodieke voortgangstoetsing, evt. permanente inspecteurs op locatie. Geschikt voor kritische componenten."},
  {cat:"operationeel", term:"Ontvangstcontrole",
   def:"Controle bij binnenkomst van een levering op: artikelen en aantallen (manco), kwaliteit (zichtbaar of via laboratorium), logistiek (verpakking, tijd, transportmiddel) en documentatie."},
  {cat:"operationeel", term:"Three-way matching",
   def:"Vergelijking van drie documenten vóórdat een factuur betaalbaar wordt gesteld: (1) inkooporder, (2) afleveringsbon, (3) factuur. Alleen bij overeenstemming wordt betaald. Voorkomt betalen voor niet-geleverde of te duur gefactureerde goederen."},
  {cat:"operationeel", term:"Leveranciersevaluatie",
   def:"Periodieke beoordeling van een leverancier op kwaliteit, leveringsbetrouwbaarheid, communicatie en prijs-kwaliteitsverhouding. Basis voor toekomstige selectiebeslissingen en contractverlengingen."},

  /* ══════════════════════════════════════════
     5. STRATEGIE — CONTRACT, SPEND, KRALJIC (Week 4)
  ══════════════════════════════════════════ */
  {cat:"strategie", term:"Uitbesteden (outsourcing)",
   def:"Strategische overdracht van intern uitgevoerde activiteiten aan een externe partij voor een langere termijn (3-7 jaar). Kenmerken: bedrijfsmiddelen gaan over, intensieve relatie, nieuw kosten- én risicoprofiel."},
  {cat:"strategie", term:"Contractmanagement",
   def:"Het geheel van activiteiten gericht op het wederzijds doen nakomen van afspraken tussen leveranciers en opdrachtgevers, zodanig dat maximale waarde voor de organisatie wordt gecreëerd. Bestaat uit contractbeheer + prestatiemanagement."},
  {cat:"strategie", term:"Contractbeheer",
   def:"Administratief beheren en archiveren van contracten. Bijhouden van expiratiedata, mutaties en stuurinformatie. Doel: interne organisatie voorzien van actuele contractinformatie."},
  {cat:"strategie", term:"Prestatiemanagement",
   def:"Actief monitoren en sturen op afgesproken prestaties (KPI's en SLA's). Periodieke evaluatiegesprekken met leveranciers gericht op continue verbetering."},
  {cat:"strategie", term:"Leveranciersmanagement",
   def:"Alle activiteiten gericht op het verkennen, selecteren, starten, onderhouden, ontwikkelen en beëindigen van leveranciersrelaties. Doel: continu optimale bijdrage aan organisatiedoelstellingen. Gaat verder dan contractmanagement — omvat ook co-innovatie en partnership."},
  {cat:"strategie", term:"Spendanalyse",
   def:"Financiële analyse naar de daadwerkelijke inkoopuitgaven van een organisatie. Beantwoordt acht vragen: wat, hoeveel, bij wie, hoe vaak, welke afdeling, maverick buying-aandeel, aantal facturen, gemiddelde factuurwaarde."},
  {cat:"strategie", term:"ABC-analyse",
   def:"Indeling van leveranciers of artikelen in drie categorieën op basis van inkoopomzet. A: ~20% leveranciers, ~80% omzet. B: ~30% leveranciers, ~15% omzet. C: ~50% leveranciers, ~5% omzet."},
  {cat:"strategie", term:"Pareto-principe (80/20-regel)",
   def:"Empirisch principe: 20% van de leveranciers is verantwoordelijk voor 80% van de inkoopuitgaven. Basis voor de ABC-analyse en prioritering van inkoopactiviteiten."},
  {cat:"strategie", term:"Kraljic-matrix",
   def:"Portfoliomodel waarbij inkopen worden ingedeeld op basis van financiële invloed (hoog/laag) × toeleveringsrisico (hoog/laag). Geeft vier kwadranten: strategisch, hefboom, knelpunt en routine — elk met een eigen strategie."},
  {cat:"strategie", term:"Strategische producten (Kraljic)",
   def:"Hoog toeleveringsrisico + hoge financiële invloed. Van één leverancier; grote waarde in kostprijs. Bijv. motoren autofabriek, IT-mainframes. Strategie: strategic partnership, open calculatie, co-innovatie."},
  {cat:"strategie", term:"Hefboomproducten (Kraljic)",
   def:"Laag toeleveringsrisico + hoge financiële invloed. Van meerdere leveranciers; grote waarde; kleine prijswijziging heeft groot effect. Bijv. bulkchemicaliën, grondstoffen. Strategie: concurrentiestelling, breed uitvragen."},
  {cat:"strategie", term:"Knelpuntproducten (Kraljic)",
   def:"Hoog toeleveringsrisico + lage financiële invloed. Van één leverancier; relatief geringe waarde maar kwetsbaar. Bijv. machine-specifieke reserveonderdelen. Strategie: veiligstellen toelevering, buffervoorraden."},
  {cat:"strategie", term:"Routineproducten (Kraljic)",
   def:"Laag toeleveringsrisico + lage financiële invloed. Van veel leveranciers; geringe waarde per eenheid; meeste producten vallen hieronder. Bijv. kantoorartikelen, schoonmaakmiddelen. Strategie: digitaliseren en automatiseren."},
  {cat:"strategie", term:"Exitafspraken",
   def:"Contractuele bepalingen over hoe een samenwerking beëindigd kan worden: overdrachtsperiode, eigendom van data en bedrijfsmiddelen, kennisoverdracht. Essentieel bij uitbesteding om vendor lock-in te voorkomen."},

  /* ══════════════════════════════════════════
     6. INKOOPMARKTONDERZOEK & PMI (Week 5)
  ══════════════════════════════════════════ */
  {cat:"markt", term:"Inkoopmarktonderzoek",
   def:"Systematisch onderzoek naar alle relevante factoren die de verwerving van goederen en diensten beïnvloeden. Doel: huidige en toekomstige behoeften veiligstellen en de concurrentiepositie versterken."},
  {cat:"markt", term:"Macro-economische factoren",
   def:"Algemene economische omgeving: conjunctuur, loonontwikkelingen, rentestand, wetgeving, grondstofprijzen, valuta, inflatie, geopolitieke spanningen. Beïnvloeden prijsontwikkelingen en leveringszekerheid."},
  {cat:"markt", term:"Meso-economische factoren",
   def:"Ontwikkelingen in een specifieke bedrijfstak: vraag-aanbodverhouding, orderportefeuilles, bezettingsgraad, marktstructuur (oligopolie, monopolie, vrije markt). Helpen inschatten hoe 'krap' of 'ruim' de markt is."},
  {cat:"markt", term:"Micro-economische factoren",
   def:"Kenmerken van het individuele leveranciersbedrijf: financiële positie, managementstructuur, leveringsbetrouwbaarheid, kwaliteitsprestaties, kostprijsstructuur. Geeft inzicht in betrouwbaarheid en continuïteitsrisico."},
  {cat:"markt", term:"Productfactoren",
   def:"Factoren die de verkoopprijs en kostprijs van een product of dienst bepalen: technische specs, substituten, standaardisatie, innovatiecyclus, levertijden, certificeringen."},
  {cat:"markt", term:"PMI (Purchasing Managers Index)",
   def:"Indicator voor economische bedrijvigheid, ontleend aan het inkoopvolume dat inkopers in een bepaalde maand contracteren. PMI > 50 = groei; PMI < 50 = krimp. Gepubliceerd door NEVI, iedere eerste werkdag van de maand."},
  {cat:"markt", term:"NEVI",
   def:"Nederlandse Vereniging voor Inkoop Management. Publiceert maandelijks de PMI en is de beroepsvereniging voor inkoopprofessionals in Nederland."},
  {cat:"markt", term:"Dataleveranciers (Graydon, Dun & Bradstreet)",
   def:"Commerciële databedrijven die grote databases beheren met financiële gegevens van bedrijven in EU-landen. Gebruikt om snel een beeld te krijgen van de financiële situatie en kredietwaardigheid van potentiële leveranciers."},

  /* ══════════════════════════════════════════
     7. DIGITALISERING (Week 3)
  ══════════════════════════════════════════ */
  {cat:"digitaal", term:"Inkoopdigitalisering",
   def:"Het gebruik van ICT om klant, leverancier en andere partners in een waardeketen met elkaar te verbinden, zodanig dat de prestaties van transactieprocessen worden verbeterd."},
  {cat:"digitaal", term:"ERP (Enterprise Resource Planning)",
   def:"Geïntegreerd softwaresysteem dat alle bedrijfsprocessen (Finance, Operations, HRM, Inkoop) ondersteunt vanuit één centrale database. Ruggengraat van de informatievoorziening in grotere organisaties. Bekende leveranciers: SAP, Oracle."},
  {cat:"digitaal", term:"AI (Artificial Intelligence) in inkoop",
   def:"Systemen die menselijke intelligentie nabootsen en zichzelf verbeteren via data. Toepassingen in inkoop: chatbots, automatische contractopstelling, forecasting van volumes en prijzen. Voorbeelden: ChatGPT, Copilot, Brainial."},
  {cat:"digitaal", term:"RPA (Robotic Process Automation)",
   def:"Automatisering van repetitieve bedrijfsprocessen via software. Inkoop-toepassing: automatische factuurafhandeling door vergelijking van magazijnsysteem, contractsysteem en crediteurenadministratie (three-way matching)."},
  {cat:"digitaal", term:"Blockchain & Smart Contracts",
   def:"Blockchain = gedistribueerde registratie van data in blokken; geen centrale autoriteit nodig. Smart contracts voeren afspraken automatisch uit bij vooraf bepaalde criteria. Inkoop-toepassing: herkomst producten traceren, automatische betaling bij levering."},
  {cat:"digitaal", term:"IoT (Internet of Things)",
   def:"Apparaten die via internet met elkaar communiceren. Inkoop-toepassing: machine stuurt signaal bij naderende storing → preventief onderhoud bestellen; automatische voorraadbewaking en nabestelling."},
  {cat:"digitaal", term:"Data-analyse & visualisatie",
   def:"Tools (Power BI, Qlikview) die data uit meerdere bronnen combineren en visualiseren. Algoritmen ondersteunen besluitvorming in inkoop: spend-analyse, leveranciersprestaties, contractverloop."},
  {cat:"digitaal", term:"Inkoper van de toekomst",
   def:"De toekomstvisie: operationele inkoop wordt volledig geautomatiseerd door computers. De inkoper wordt een businessanalist die zich richt op strategie, leveranciersrelaties en innovatie in plaats van routinetransacties."},

  /* MVI — duurzaam inkopen */
  {cat:"mvi", term:"MVI (Maatschappelijk Verantwoord Inkopen)",
   def:"Inkopen waarbij naast prijs en kwaliteit ook gelet wordt op de impact op mens, milieu en maatschappij (3 P's: Planet, People, Profit). Voor Nederlandse overheden verplicht; in de private sector gestimuleerd door CSRD-rapportage."},
  {cat:"mvi", term:"Circulair inkopen",
   def:"Inkoopstrategie gericht op zo lang mogelijk hergebruiken van grondstoffen en producten. Instrumenten: kopen op gebruik (Product-as-a-Service), retourgaranties, hergebruik en remanufacturing als contractvoorwaarde."},
  {cat:"mvi", term:"SROI (Social Return on Investment)",
   def:"Verplichting in een inkoopcontract om een percentage van de loonsom (vaak 5%) in te zetten voor mensen met afstand tot de arbeidsmarkt. Vooral in publieke aanbestedingen toegepast."},
  {cat:"mvi", term:"BPKV / EMVI",
   def:"Beste Prijs-Kwaliteit Verhouding (in Aanbestedingswet sinds 2016 de standaardterm; eerder EMVI = Economisch Meest Voordelige Inschrijving). Gunningscriterium waarbij prijs én kwaliteit én duurzaamheid wegen — niet alleen de laagste prijs."},
  {cat:"mvi", term:"CO₂-prestatieladder",
   def:"Nederlands certificeringsinstrument dat organisaties beoordeelt op hun inspanning om CO₂-uitstoot te reduceren. Veel gebruikt als geschiktheidseis of gunningsvoordeel in (publieke) aanbestedingen."},

  /* Wanprestatie van leveranciers */
  {cat:"wanprestatie", term:"Wanprestatie (toerekenbare tekortkoming)",
   def:"De leverancier komt zijn verbintenis niet, niet op tijd of niet goed na (art. 6:74 BW). Inkoop reageert via het BW: tekortkoming vaststellen → ingebrekestelling (6:82) → verzuim (6:81) → schadevergoeding of ontbinding (6:265)."},
  {cat:"wanprestatie", term:"Opschorting (art. 6:262 BW)",
   def:"De afnemer mag zijn eigen prestatie (bijv. betaling) tijdelijk uitstellen zolang de leverancier zijn verplichting niet nakomt. Drukmiddel zonder dat het contract eindigt."},
  {cat:"wanprestatie", term:"Bankgarantie / boete-/bonusregeling",
   def:"Contractuele zekerheden die wanprestatie verzachten of belonen. Bankgarantie: bank betaalt afnemer een afgesproken bedrag bij tekortkoming. Boete: vooraf afgesproken bedrag dat de leverancier verschuldigd is. Bonus: extra vergoeding bij overprestatie."},
  {cat:"wanprestatie", term:"Escalatieladder (in SLA)",
   def:"Vooraf vastgelegde stappen om geschillen op te lossen: operationeel overleg → tactisch overleg → directieoverleg → mediation → arbitrage of rechter. Voorkomt dat één incident direct in een rechtszaak eindigt."},

];;
INKOOP.flashcards = [
  /* ── BASISPRINCIPES ── */
  {cat:"basis",term:"Inkoop",def:"Het van externe bronnen betrekken van alle goederen en diensten die noodzakelijk zijn voor de bedrijfsvoering en de instandhouding van een organisatie, tegen de meest gunstige voorwaarden."},
  {cat:"basis",term:"Inkoopfunctie",def:"Het organisatiebrede proces van inkoop — omvat meer dan alleen de inkoopafdeling. Factuurafhandeling (Finance), inhuren tijdelijk personeel (HRM) en boeken van transport (Logistiek) vallen buiten de afdeling maar zijn onderdeel van de inkoopfunctie."},
  {cat:"basis",term:"Spin in het web",def:"Metafoor voor de inkoper: inkoop raakt alle bedrijfsfuncties en vormt de schakel tussen de interne organisatie en de externe leveranciersmarkt."},
  {cat:"basis",term:"Primaire (directe) inkoop",def:"Inkoop van goederen en diensten die rechtstreeks terechtkomen in het eindproduct of de kernactiviteit van de organisatie. Bijv. grondstoffen voor een fabriek, medicijnen in een ziekenhuis."},
  {cat:"basis",term:"Indirecte inkoop / Facilitaire inkoop",def:"Alle inkoop voor het functioneren van de organisatie in het algemeen, los van het primaire proces. Bijv. schoonmaak, catering, beveiliging, ICT, bedrijfskleding. Dit is het werkterrein van de Facility Manager."},
  {cat:"basis",term:"MRO (Maintenance, Repair & Operations)",def:"Productcategorie binnen indirecte inkoop: goederen en diensten voor dagelijks onderhoud, reparatie en bedrijfsvoering (smeermiddelen, reserveonderdelen, gereedschap, schoonmaakartikelen). MRO wordt vaak via indirecte/facilitaire inkoop ingekocht, maar is geen synoniem ervan: het is een productsoort, niet de inkoopfunctie zelf."},
  {cat:"basis",term:"Inkoopquote",def:"Percentage van de omzet dat besteed wordt aan inkoop.",formula:"Inkoopquote = (inkoopkosten / omzet) × 100%"},
  {cat:"basis",term:"Hefboomwerking van inkoop",def:"Bij een inkoopquote van 50% en nettomarge van 5% levert 1% inkoopbesparing evenveel resultaatverbetering op als ±10% omzetgroei. Inkoop heeft directe invloed op het bedrijfsresultaat."},
  {cat:"basis",term:"Make-or-buy beslissing",def:"De meest fundamentele strategische inkoopbeslissing: voert de organisatie een activiteit zelf uit (make) of koopt ze die in bij een externe partij (buy)? Kernactiviteiten worden vaak intern gehouden."},
  {cat:"basis",term:"Maverick buying",def:"Medewerkers die buiten de gesloten contracten om inkopen. Gevolg: volume- en kortingsvoordelen gaan verloren, administratieve chaos en een slechtere onderhandelingspositie."},
  {cat:"basis",term:"Publieke inkoop",def:"Inkoop door overheidsorganisaties. Gericht op maatschappelijke doelstellingen. Boven drempelwaarden verplicht Europees aanbesteden met gelijke kansen voor leveranciers."},
  {cat:"basis",term:"Private inkoop",def:"Inkoop door private organisaties (bedrijven, instellingen). Gericht op winst of continuïteit. Vrij in leverancierskeuze en onderhandelingswijze."},
  {cat:"basis",term:"Aanbesteding",def:"Formeel proces waarmee een opdrachtgever de markt benadert om leveranciers te selecteren. Verplicht bij publieke organisaties boven bepaalde drempelwaarden."},
  {cat:"basis",term:"Centrale inkoop",def:"Één centrale afdeling is verantwoordelijk voor alle inkoop. Voordeel: maximale schaalvoordelen. Nadeel: ver van de business, beperkte lokale zeggenschap."},
  {cat:"basis",term:"Decentrale inkoop",def:"Afdelingen of businessunits kopen zelf in. Voordeel: lokale kennis. Nadeel: verlies van schaalvoordelen en mogelijk hogere prijzen."},
  {cat:"basis",term:"Hybride inkoop (coördinatie)",def:"Combinatie van centrale regie en decentrale uitvoering. Combineert schaalvoordelen met flexibiliteit."},
  {cat:"basis",term:"Vier primaire taken van inkoop",def:"1. Operationele excellentie (continuïteit), 2. Realiseren van inkoopbesparingen, 3. Verminderen van risico's in de toeleveringsketen, 4. Bijdragen aan innovatie en waardecreatie."},

  /* ── VAN WEELE (6 STAPPEN) ── */
  {cat:"vanweele",term:"Lineair inkoopproces van Van Weele",def:"Zes stappen: 1. Specificeren → 2. Selecteren → 3. Contracteren (tactisch, éénmalig) → 4. Bestellen → 5. Bewaken → 6. Nazorg & Evaluatie (operationeel, herhaald)."},
  {cat:"vanweele",term:"Tactische inkoop (stappen 1-3)",def:"De éénmalige, strategische fase: specificeren, selecteren en contracteren. Bepaalt wat, bij wie en onder welke voorwaarden wordt ingekocht."},
  {cat:"vanweele",term:"Operationele inkoop (stappen 4-6)",def:"De herhaalde, uitvoerende fase: bestellen, bewaken en nazorg & evaluatie. Wordt gedurende de looptijd van een contract steeds opnieuw doorlopen."},
  {cat:"vanweele",term:"Stap 1: Specificeren",def:"Bepalen wát er ingekocht moet worden. Primair de verantwoordelijkheid van de gebruiker/budgethouder. De inkoper zorgt dat de specificatie objectief en eenduidig is."},
  {cat:"vanweele",term:"Stap 2: Selecteren",def:"Markt in kaart brengen, shortlist opstellen, offertes aanvragen (RFQ) en de meest geschikte leverancier kiezen op basis van een gestructureerde beoordelingsmethode."},
  {cat:"vanweele",term:"Stap 3: Contracteren",def:"Onderhandelen over prijs en voorwaarden, en de afspraken vastleggen in een contract. Bevat afspraken over prijs, kwaliteit, levering, KPI's, SLA's en exitclausules."},
  {cat:"vanweele",term:"Stap 4: Bestellen",def:"Het plaatsen van een inkooporder bij de gecontracteerde leverancier. De inkooporder is de officiële bevestiging van een bestelling."},
  {cat:"vanweele",term:"Stap 5: Bewaken (orderbewaking)",def:"Toezicht houden op tijdige, volledige levering. Drie methoden: exception expediting, routine statuscheck, advanced statuscheck."},
  {cat:"vanweele",term:"Stap 6: Nazorg & Evaluatie",def:"Factuurcontrole via three-way matching, afhandeling van reclames en leveranciersbeoordeling. Basis voor toekomstige selectiebeslissingen."},

  /* ── TACTISCHE INKOOP ── */
  {cat:"tactisch",term:"Functionele specificatie",def:"Beschrijft wát een product of dienst moet doen (niet hóe). Geeft leveranciers ruimte voor creatieve oplossingen. Voorbeeld: 'De ruimte moet schoon zijn.'"},
  {cat:"tactisch",term:"Programma van Eisen (PvE)",def:"Verdere detaillering van de functionele specificatie met SMART-geformuleerde eisen, richtbudget en randvoorwaarden."},
  {cat:"tactisch",term:"Technische specificatie",def:"Uitwerking van alle specifieke technische eisen: maatvoering, materialen, normen, levertijden, certificeringen. Het meest gedetailleerde niveau van specificeren."},
  {cat:"tactisch",term:"Eisen vs. wensen",def:"Eisen zijn knock-outcriteria — leveranciers die niet voldoen worden uitgesloten. Wensen zijn nice-to-have criteria die meewegen in de beoordeling maar niet elimineren."},
  {cat:"tactisch",term:"Best Value Procurement (BVP)",def:"Inkoopstrategie waarbij de nadruk ligt op de best mogelijke waarde, niet op de laagste prijs."},
  {cat:"tactisch",term:"RFI (Request for Information)",def:"Informatieverzoek aan potentiële leveranciers in de oriëntatiefase. Niet bindend. Gebruikt voor marktconsultatie en prekwalificatie: longlist → shortlist."},
  {cat:"tactisch",term:"RFQ (Request for Quotation)",def:"Formele offerteaanvraag bij de shortlist van leveranciers. Bindend bij gunning. Bevat alle eisen en criteria waarop beoordeeld wordt."},
  {cat:"tactisch",term:"Prekwalificatie",def:"Toetsen of potentiële leveranciers voldoen aan basisvereisten vóórdat een formele offerteaanvraag wordt gedaan. Longlist → shortlist."},
  {cat:"tactisch",term:"Gewogen factorscore / BPKV",def:"Offertebeoordelingsmethode waarbij meerdere criteria elk een wegingsfactor krijgen. Meest gebruikt bij complexe aankopen. BPKV = Best Price to Quality Value."},
  {cat:"tactisch",term:"Indexmethode",def:"Offertebeoordelingsmethode waarbij een vaste prijs/kwaliteitsverhouding is vastgesteld (bijv. 50/50). 1% hogere kwaliteit rechtvaardigt 1% hogere prijs."},
  {cat:"tactisch",term:"Waardering in euro's",def:"Offertebeoordelingsmethode waarbij kwaliteitsverschillen worden uitgedrukt in euro's en in mindering worden gebracht op de aangeboden prijs. De laagste gecorrigeerde prijs wint."},
  {cat:"tactisch",term:"Accountportfolio",def:"Spiegel van de Kraljic-matrix vanuit leveranciersperspectief: hoe segmenteert de leverancier zijn klanten? Core account (hoge omzet, strategisch), Development account, Nuisance account."},
  {cat:"tactisch",term:"Resultaatcontract",def:"Contract waarbij de leverancier een concreet resultaat garandeert. Betaling is gekoppeld aan het resultaat. Makkelijker toetsbaar — voorkeur van de inkoper."},
  {cat:"tactisch",term:"Inspanningscontract",def:"Contract waarbij de leverancier zich inspant maar geen resultaat garandeert (bijv. advocaat, adviseur). Van toepassing als het eindresultaat moeilijk van tevoren te definiëren is."},
  {cat:"tactisch",term:"Vaste prijs (fixed price)",def:"Contractvorm waarbij de prijs vooraf is vastgesteld. Het financiële risico ligt bij de leverancier. Vereist een volledig en gedetailleerd PvE."},
  {cat:"tactisch",term:"Regiecontract",def:"Contractvorm waarbij achteraf wordt verrekend op basis van uren en materialen. Financieel risico ligt bij de opdrachtgever. Biedt de leverancier geen prikkel voor efficiëntie."},
  {cat:"tactisch",term:"Eenheidsprijscontract",def:"Contractvorm met een tarief per prestatie-eenheid (m², uur, stuk). Geschikt voor standaard terugkerende werkzaamheden waarbij volume vooraf onbekend is."},
  {cat:"tactisch",term:"SLA (Service Level Agreement)",def:"Meetbare prestatieafspraken over het niveau van dienstverlening. Onderdeel van het contract. Basis voor het beoordelen van de leverancier tijdens de operationele fase."},
  {cat:"tactisch",term:"KPI (Key Performance Indicator)",def:"Prestatie-indicator waarmee de kwaliteit van levering wordt gemeten. Wordt gebruikt bij orderbewaking, leveranciersevaluatie en contractmanagement."},
  {cat:"tactisch",term:"Salamitactiek",def:"Onderhandelingstactiek waarbij in kleine stappen concessies worden verkregen, zodat de wederpartij niet in één keer het totale verlies ziet."},
  {cat:"tactisch",term:"TCO (Total Cost of Ownership)",def:"Alle kosten verbonden aan de aanschaf, het bezit en de afdanking van een product over de volledige levenscyclus. Nadrukkelijk niet alleen de aanschafprijs.",formula:"TCO = pre-transactie + transactie + post-transactiekosten"},

  /* ── OPERATIONELE INKOOP ── */
  {cat:"operationeel",term:"Inkooporder",def:"Officieel document waarmee de koper een bestelling plaatst bij een leverancier na ondertekening van het contract."},
  {cat:"operationeel",term:"Roundtrip bestelling",def:"Bestelwijze waarbij de medewerker winkelt in de webshop van de leverancier; het winkelmandje wordt teruggezonden naar het interne bestelsysteem voor goedkeuring."},
  {cat:"operationeel",term:"Catalogusbestelling",def:"Bestelwijze waarbij de medewerker winkelt in een interne catalogus. Snelle route: direct naar budgethouder ter goedkeuring."},
  {cat:"operationeel",term:"Vrije aanvraag",def:"Bestelwijze voor niet-standaard bestellingen. Langste route: eerst langs Inkoop en Bedrijfsbureau, dan naar budgethouder."},
  {cat:"operationeel",term:"Exception expediting (piepsysteem)",def:"Reactieve bewakingsmethode waarbij de inkoper pas actie onderneemt na een probleemsignaal. Nadeel: inkoper loopt altijd achter de feiten aan."},
  {cat:"operationeel",term:"Routine statuscheck",def:"Proactieve bewakingsmethode waarbij de inkoper enkele dagen vóór de leverdatum contact opneemt om leverdatum en volledigheid te bevestigen."},
  {cat:"operationeel",term:"Advanced statuscheck",def:"Meest proactieve bewakingsmethode: kritische leveranciers geven een gedetailleerde productieplanning; periodieke voortgangstoetsing. Geschikt voor kritische componenten."},
  {cat:"operationeel",term:"Ontvangstcontrole",def:"Controle bij binnenkomst van een levering op: artikelen en aantallen (manco), kwaliteit, logistiek (verpakking, tijd) en documentatie."},
  {cat:"operationeel",term:"Three-way matching",def:"Vergelijking van drie documenten vóórdat een factuur betaalbaar wordt gesteld: (1) inkooporder, (2) afleveringsbon, (3) factuur. Alleen bij overeenstemming wordt betaald."},
  {cat:"operationeel",term:"Leveranciersevaluatie",def:"Periodieke beoordeling van een leverancier op kwaliteit, leveringsbetrouwbaarheid, communicatie en prijs-kwaliteitsverhouding."},

  /* ── STRATEGIE & CONTRACTEN ── */
  {cat:"strategie",term:"Uitbesteden (outsourcing)",def:"Strategische overdracht van intern uitgevoerde activiteiten aan een externe partij voor een langere termijn (3-7 jaar). Kenmerken: bedrijfsmiddelen gaan over, intensieve relatie."},
  {cat:"strategie",term:"Contractmanagement",def:"Het geheel van activiteiten gericht op het wederzijds doen nakomen van afspraken, zodanig dat maximale waarde voor de organisatie wordt gecreëerd. Bestaat uit contractbeheer + prestatiemanagement."},
  {cat:"strategie",term:"Contractbeheer",def:"Administratief beheren en archiveren van contracten. Bijhouden van expiratiedata, mutaties en stuurinformatie."},
  {cat:"strategie",term:"Prestatiemanagement",def:"Actief monitoren en sturen op afgesproken prestaties (KPI's en SLA's). Periodieke evaluatiegesprekken met leveranciers gericht op continue verbetering."},
  {cat:"strategie",term:"Leveranciersmanagement",def:"Alle activiteiten gericht op het verkennen, selecteren, starten, onderhouden, ontwikkelen en beëindigen van leveranciersrelaties. Gaat verder dan contractmanagement — omvat ook co-innovatie."},
  {cat:"strategie",term:"Spendanalyse",def:"Financiële analyse naar de daadwerkelijke inkoopuitgaven. Beantwoordt acht vragen: wat, hoeveel, bij wie, hoe vaak, welke afdeling, maverick buying-aandeel, aantal facturen, gemiddelde factuurwaarde."},
  {cat:"strategie",term:"ABC-analyse",def:"Indeling van leveranciers of artikelen op basis van inkoopomzet. A: ~20% leveranciers, ~80% omzet. B: ~30% leveranciers, ~15% omzet. C: ~50% leveranciers, ~5% omzet."},
  {cat:"strategie",term:"Pareto-principe (80/20-regel)",def:"Empirisch principe: 20% van de leveranciers is verantwoordelijk voor 80% van de inkoopuitgaven. Basis voor de ABC-analyse."},
  {cat:"strategie",term:"Kraljic-matrix",def:"Portfoliomodel waarbij inkopen worden ingedeeld op financiële invloed (hoog/laag) × toeleveringsrisico (hoog/laag). Vier kwadranten: strategisch, hefboom, knelpunt en routine."},
  {cat:"strategie",term:"Strategische producten (Kraljic)",def:"Hoog toeleveringsrisico + hoge financiële invloed. Van één leverancier; grote waarde in kostprijs. Bijv. motoren autofabriek. Strategie: strategic partnership, open calculatie, co-innovatie."},
  {cat:"strategie",term:"Hefboomproducten (Kraljic)",def:"Laag toeleveringsrisico + hoge financiële invloed. Van meerdere leveranciers; kleine prijswijziging heeft groot effect. Bijv. bulkchemicaliën. Strategie: concurrentiestelling, breed uitvragen."},
  {cat:"strategie",term:"Knelpuntproducten (Kraljic)",def:"Hoog toeleveringsrisico + lage financiële invloed. Van één leverancier; relatief geringe waarde maar kwetsbaar. Bijv. machine-specifieke reserveonderdelen. Strategie: veiligstellen toelevering."},
  {cat:"strategie",term:"Routineproducten (Kraljic)",def:"Laag toeleveringsrisico + lage financiële invloed. Van veel leveranciers; geringe waarde per eenheid. Bijv. kantoorartikelen. Strategie: digitaliseren en automatiseren."},
  {cat:"strategie",term:"Exitafspraken",def:"Contractuele bepalingen over hoe een samenwerking beëindigd kan worden: overdrachtsperiode, eigendom van data en bedrijfsmiddelen. Essentieel bij uitbesteding om vendor lock-in te voorkomen."},

  /* ── MARKTONDERZOEK & PMI ── */
  {cat:"markt",term:"Inkoopmarktonderzoek",def:"Systematisch onderzoek naar alle relevante factoren die de verwerving van goederen en diensten beïnvloeden. Doel: huidige en toekomstige behoeften veiligstellen."},
  {cat:"markt",term:"Macro-economische factoren",def:"Algemene economische omgeving: conjunctuur, loonontwikkelingen, rentestand, wetgeving, grondstofprijzen, valuta, inflatie, geopolitieke spanningen."},
  {cat:"markt",term:"Meso-economische factoren",def:"Ontwikkelingen in een specifieke bedrijfstak: vraag-aanbodverhouding, orderportefeuilles, bezettingsgraad, marktstructuur (oligopolie, monopolie, vrije markt)."},
  {cat:"markt",term:"Micro-economische factoren",def:"Kenmerken van het individuele leveranciersbedrijf: financiële positie, managementstructuur, leveringsbetrouwbaarheid, kwaliteitsprestaties, kostprijsstructuur."},
  {cat:"markt",term:"Productfactoren",def:"Factoren die de verkoopprijs en kostprijs bepalen: technische specs, substituten, standaardisatie, innovatiecyclus, levertijden, certificeringen."},
  {cat:"markt",term:"PMI (Purchasing Managers Index)",def:"Indicator voor economische bedrijvigheid, ontleend aan het inkoopvolume dat inkopers in een bepaalde maand contracteren. PMI > 50 = groei; PMI < 50 = krimp."},
  {cat:"markt",term:"NEVI",def:"Nederlandse Vereniging voor Inkoop Management. Publiceert maandelijks de PMI en is de beroepsvereniging voor inkoopprofessionals in Nederland."},
  {cat:"markt",term:"Dataleveranciers (Graydon, Dun & Bradstreet)",def:"Commerciële databedrijven die databases beheren met financiële gegevens van bedrijven. Gebruikt om snel inzicht te krijgen in de kredietwaardigheid van potentiële leveranciers."},

  /* ── DIGITALISERING ── */
  {cat:"digitaal",term:"Inkoopdigitalisering",def:"Het gebruik van ICT om klant, leverancier en andere partners in een waardeketen te verbinden, zodanig dat de prestaties van transactieprocessen worden verbeterd."},
  {cat:"digitaal",term:"ERP (Enterprise Resource Planning)",def:"Geïntegreerd softwaresysteem dat alle bedrijfsprocessen ondersteunt vanuit één centrale database. Ruggengraat van de informatievoorziening. Bekende leveranciers: SAP, Oracle."},
  {cat:"digitaal",term:"AI (Artificial Intelligence) in inkoop",def:"Systemen die menselijke intelligentie nabootsen. Toepassingen in inkoop: chatbots, automatische contractopstelling, forecasting van volumes en prijzen."},
  {cat:"digitaal",term:"RPA (Robotic Process Automation)",def:"Automatisering van repetitieve bedrijfsprocessen via software. Inkoop-toepassing: automatische factuurafhandeling door vergelijking van drie systemen (three-way matching)."},
  {cat:"digitaal",term:"Blockchain & Smart Contracts",def:"Blockchain = gedistribueerde registratie van data in blokken. Smart contracts voeren afspraken automatisch uit bij vooraf bepaalde criteria. Inkoop-toepassing: herkomst producten traceren."},
  {cat:"digitaal",term:"IoT (Internet of Things)",def:"Apparaten die via internet met elkaar communiceren. Inkoop-toepassing: machine stuurt signaal bij naderende storing → preventief onderhoud bestellen; automatische voorraadbewaking."},
  {cat:"digitaal",term:"Data-analyse & visualisatie",def:"Tools (Power BI, Qlikview) die data uit meerdere bronnen combineren en visualiseren. Ondersteunen besluitvorming in inkoop: spend-analyse, leveranciersprestaties, contractverloop."},
  {cat:"digitaal",term:"Inkoper van de toekomst",def:"Operationele inkoop wordt volledig geautomatiseerd. De inkoper wordt een businessanalist die zich richt op strategie, leveranciersrelaties en innovatie in plaats van routinetransacties."},
];;
